seed: 1
algorithm: dct
net: fno2d
dataset: sw2d_pda
save_name: fno_sw2d_pda_1
save_dir: ./saved_models/ours_dct/fno/
load_path: ./saved_models/ours_dct/fno/fno_sw2d_pda_1/latest_model.pth
# 
resume: false
overwrite: true
use_tensorboard: false
dataset_type: temporal
normalize: false
# FOR DATASET CONFIGURATIONS
img_size: 96, 192
res: 192
n_channels: 2
T_in: 2
T_ar: 5
T_bundle: 1
noise_scale: 0.0
# noise_scale: 0.0005
# FOR OPTIMIZATION CONFIGURATIONS
epochs: 500
num_train_iter: 150000
num_eval_iter: 300
num_log_iter: 100
batch_size: 32
eval_batch_size: 32
# 
optim: adamw
beta1: 0.9
beta2: 0.999
# 
clip_grad: 5.0
warmup_epochs: 50
weight_decay: 1e-6
lr: 0.001
lr_method: cycle
# FOR TRAINING CONFIGURATIONS
train_sampler: RandomSampler
num_workers: 8
world_size: 1
rank: 0
multiprocessing_distributed: false
dist_url: tcp://127.0.0.1:22647
dist_backend: nccl
gpu: None
# FNO SPECIFIC CONFIGURATIONS
modes1: 12
modes2: 12
modes3: 12
width: 20
n_layers: 4
padding: 0,0
use_ln: false
# FOR ADDITIONAL TRAINING CONFIGURATIONS
use_tf: ture
# use_tf: false
use_dcm: true
# use_dcm: false
use_sampler: false